.PHONY: local docker

local:
	./install-dependencies.sh
docker:
	@echo "Victime des mise à jour de la librairie abe-lsss"
#	docker build --no-cache -t presto-content-filtering-use-case:relic-0.6.0--lsss-1.0 .